### ISSUE TITLE
파이썬 서버 코드

### ISSUE THREAD

**Issue by dding-g** [PowerSH/HackerTrain#4]
#!/usr/bin/env python
import socket
import thread

HOST = '210.115.226.109'
PORT = 10080

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind((HOST, PORT))
s.listen(1)

conn, addr = s.accept()
print 'Connected by', addr
data = ''\

def pr_msg():
    while 1:
        data = conn.recv(1024)
        if data:
           print data.upper()

thread.start_new_thread(pr_msg, ())

while 1:
    send_data = raw_input()
    if send_data[:4] in ['quit', 'Quit', 'QUIT']:        conn.send('Server Quit')
        thread.exit()
        conn.close()
    conn.send('Server : ' + send_data)

**Comment by area409** [comment]
#!/usr/bin/env python
import os
import sys
from operator import eq
from socket import *
import thread
import copy

port = 11111
host = '210.115.226.109'

def serv((c,addr)):
        print('conndection : {}{}'.format(c,addr[0]))
        users.append(c)
        if(eq(addr[0],'220.66.155.132')):
                try:
                        str1 = '[' + addr[0] +'has entered]'
                        while c:
                                print str1
                                data = c.recv(1).decode()
                                for each in users:
                                        if c!= each:
                                                each.send(data)
                                                print(data)
                                                c.close()
                except ValueError:
                         users.remove(c)
                         str1 = '['+addr+'has exit]'
                         print str1

global users
s = socket(AF_INET, SOCK_STREAM)
s.bind((host,port))
s.listen(5)
users=[]

while 1:
    print('ready server')
    thread.start_new_thread(serv, (s.accept(),))

**Comment by dding-g** [comment]
##최종본##
#!/usr/bin/env python
import os
import sys
from operator import eq
from socket import *
import thread
import copy

port = 11111
host = '210.115.226.109'
dataSave = ''

def serv((c,addr)):
        global dataSave
        print('conndection : {}{}'.format(c,addr[0]))
        users.append(c)
        str1 = '[' + addr[0] +'has entered]'
        data = c.recv(1024)
        dataName = data.split(':')
        if eq(dataName[0], 'pi'):
                print(dataName)
                dataSave = dataName[1]+'\n'
        while c.recv(1024):
                if eq(dataName[0], 'and'):
                        for i in users:
                                if i == c:
                                        print 'i == c : ', dataSave
                                        i.send(dataSave)

global users
s = socket(AF_INET, SOCK_STREAM)
s.bind((host,port))
s.listen(5)
users=[]

while 1:
    print('ready server')
    thread.start_new_thread(serv, (s.accept(),))
